//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crookies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crookie
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> X2 { get; set; }
        public Nullable<int> Y2 { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string Camera { get; set; }
        public string DetectionScore { get; set; }
    }
}
